### ISSUE TITLE
Login issues 

### ISSUE THREAD

**Issue by edent** [edent/openbenches#185]
As reported by a user. Seen in the logs.
```
PHP Fatal error:  Uncaught Auth0\SDK\Exception\CoreException: Invalid state in /home/openbenc/public_html/vendor/auth0/auth0-php/src/Auth0.php:511
Stack trace:
#0 /home/openbenc/public_html/vendor/auth0/auth0-php/src/Auth0.php(434): Auth0\SDK\Auth0->exchange()
#1 /home/openbenc/public_html/login.php(30): Auth0\SDK\Auth0->getUser()
#2 {main}
  thrown in /home/openbenc/public_html/vendor/auth0/auth0-php/src/Auth0.php on line 511
```

Upgraded the Auth0 library to latest version. Will monitor.

**Comment by edent** [comment]
Seems fixed.
