### ISSUE TITLE
Twitter integration bug with images

### ISSUE THREAD

**Issue by edent** [edent/openbenches#57]
Problem getting or resizing images?
Related to #19 ?

```
[11-Aug-2017 09:59:58 Europe/London] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /home/openbenc/public_html/image.php on line 34
[11-Aug-2017 09:59:58 Europe/London] PHP Fatal error:  Uncaught Exception: Downloading a remote media file failed. in /home/openbenc/public_html/codebird.php:1865
Stack trace:
#0 /home/openbenc/public_html/codebird.php(1827): Codebird\Codebird->_fetchRemoteFile('https://openben...')
#1 /home/openbenc/public_html/codebird.php(1767): Codebird\Codebird->_buildBinaryBody('https://openben...')
#2 /home/openbenc/public_html/codebird.php(1741): Codebird\Codebird->_checkForFiles('media/upload', 'media', 'https://openben...')
#3 /home/openbenc/public_html/codebird.php(1799): Codebird\Codebird->_getMultipartRequestFromParams('media/upload', '---------------...', Array)
#4 /home/openbenc/public_html/codebird.php(2186): Codebird\Codebird->_buildMultipart('media/upload', Array)
#5 /home/openbenc/public_html/codebird.php(2307): Codebird\Codebird->_callApiPreparationsPost('POST', 'https://upload....', 'media/upload', 'media/upload', Array, true, false)
#6 /home/openbenc/public_html/codebird.php(2039): Codebird\Codebird->_callApiPreparations('POST', 'media/upload', 'media/upload in /home/openbenc/public_html/codebird.php on line 1865
```

**Comment by edent** [comment]
Specifically - https://openbenches.org/image/78cfe19ea52502bf64b4b8fabef8d5f6ff112430

Uncompresses to >200MB!
